// ui.reactproject/src/components/HomeComponent/Home.tsx
/* eslint-disable @typescript-eslint/ban-types */
import React, { useEffect, useState } from 'react';
import { GamesService } from '../GamesComponent/GamesService';
import { Game } from '../GamesComponent/game.model';
import { Image, Card, Container, Row, Col } from "react-bootstrap";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./home.component.css";
import HeroSlider from './hero/HeroSlider';
import Header from '../header/Header';
const HomeComponent: React.FC<{}> = () => {
    const [bestSellerGames, setBestSellerGames] = useState<Game[]>([]);
    const gamesService = new GamesService();
    

    useEffect(() => {
        gamesService.bestSellerGames().then((games: React.SetStateAction<Game[]>) => {
            setBestSellerGames(games);
        });
    }, []);

    return (
        <>
            <Header />
            <HeroSlider />
            <div className="container">

                <div className="section">
                    <h2 className="title">Best Saled Games</h2>
                    <Container className="d-flex p-2">
                        {bestSellerGames.map((game, index) => (
                            <Row className="justify-content-md-center">
                              <Col xs lg="2">
         
                                    <Card style={{ width: '18rem' }}>
                                        <Card.Img variant="top" src={game.imagePath} />
                                        <Card.Body>
                                            <Card.Title>{game.name}</Card.Title>
                                            <Card.Text>
                                                <div className="content">
                                                    {game.shortDescription}
                                                    <br />
                                                    <b>Release Date: </b>
                                                    <time dateTime={game.releaseDate}>
                                                        {new Date(game.releaseDate).toLocaleDateString('en-US', {
                                                            day: '2-digit',
                                                            month: 'short',
                                                            year: 'numeric',
                                                        })}
                                                    </time>
                                                </div>
                                            </Card.Text>
                                            
                                        </Card.Body>
                                    </Card>
                                </Col>
                            </Row>
                        ))}
                    </Container>
                </div>
            </div>

        </>
    );
};

export default HomeComponent;

// webui.reactproject/src/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { GamesService } from '../games/games.service';
import { Game } from '../games/game.model';
import 'rxjs/add/operator/map';

@Component({
  selector: 'gs-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  bestSellerGames: Game[];

  constructor(private gamesService: GamesService) { }

  ngOnInit() {
      this.gamesService.bestSellerGames().subscribe(x => this.bestSellerGames = x)
  }

}

<gs-hero></gs-hero>
<section class="section">
  <div class="container">
    <h2 class="title">Best Seller Games</h2>
    <div class="columns is-multiline">
      <div class="column is-one-quarter-desktop is-half-tablet" *ngFor="let game of bestSellerGames">
        <div [routerLink]="['/games', game?.id]" class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <img *ngIf='!game.imagePath' src="https://bulma.io/images/placeholders/128x128.png" alt="Placeholder image">
              <img *ngIf='game.imagePath' src="{{game.imagePath}}" alt="Placeholder image">
            </figure>
          </div>
          <div class="card-content best-seller-card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">{{game?.name}}</p>
              </div>
            </div>

            <div class="content">
              {{game?.shortDescription}}
              <br>
              <b>Release Date: </b><time>{{game?.releaseDate | date: 'dd/MMM/yyyy'}}</time>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
